packages:
  - "vike/"
  - "docs/"
  - "boilerplates/"
  - "boilerplates/*"
  - "examples/*"
  - "test/*"
  - "test-deprecated-design/*"
  - ".github/workflows/ci"

catalog:
  "@types/express": "^5.0.1"
  "express": "^5.0.1"
  "react": "^19.0.0"
  "react-dom": "^19.0.0"
  "@types/react": "^19.0.2"
  "@types/react-dom": "^19.0.2"
  "typescript": "^5.8.2"
  "vike": "0.4.227"
  "vike-node": "^0.3.5"
  "vike-react": "^0.5.12"
  "vite": "^6.2.1"

catalogs:
  react18:
    "@types/react": "^18.3.1"
    "@types/react-dom": "^18.3.1"
    "react": "^18.3.1"
    "react-dom": "^18.3.1"
    "vite": "^6.2.1"
