[files]
extend-exclude = [
    ".git/",
    "CHANGELOG.md",
    "examples/i18n/locales/translations.js",
    "test-deprecated-design/i18n/locales/translations.js",
    # Lorem ipsum
    "test/vike-react/pages/starship/+Layout.tsx",
    "test/vike-solid/pages/starship/+Layout.tsx",
    "test/vike-vue/pages/starship/DummyText.vue",
]
ignore-hidden = false

[default]
extend-ignore-re = [
    "\\[[0-9a-f]{7}\\]",
    "scss\\|styl\\|stylus",
    "(?Rm)^.*(#|//)\\s*typos-ignore$",
    # "(?Rm)^.*(#|//)\\s*spellchecker:disable-line$", # doesn't work
    # "(?s)spellchecker:ignore-next-line[^\\n]*\\n[^\\n]*", # doesn't work
]
