[files]
extend-exclude = [
    ".git/",
    "CHANGELOG.md",
]
ignore-hidden = false

[default]
extend-ignore-re = [
    "(?s)spellcheck-ignore[^\\n]*\\n[^\\n]*",
    "(?s)spellcheck-ignore:on.*?spellcheck-ignore:off",
    "(?s).*spellcheck-ignore:file.*",
]
