// `import server from 'vike:server'` — https://vike.dev/serverEntry
// Hand-written (not generated by tsc): a .ts file inside this ESM package is always a module, whereas `declare module` below needs a script.

declare module 'vike:server' {
  /**
   * Your `+server.js` composed by Vike.
   *
   * https://vike.dev/serverEntry
   */
  const server: {
    fetch: (request: Request, ...args: any[]) => Promise<Response>
  }
  export default server
}
