import '../../utils/trackLogs'

// We assume all runtime entries will load this utils.ts file
import { onLoad } from './onLoad'
onLoad()

export * from '../../utils/assert'
export * from '../../utils/cast'
export * from '../../utils/checkType'
export * from '../../utils/isCallable'
export * from '../../utils/isBrowser'
export * from '../../utils/isPlainObject'
export * from '../../utils/isPromise'
export * from '../../utils/hasProp'
export * from '../../utils/parseUrl'
export * from '../../utils/parseUrl-extras'
export * from '../../utils/slice'
export * from '../../utils/sorter'
export * from '../../utils/projectInfo'
export * from '../../utils/isArray'
export * from '../../utils/isObject'
export * from '../../utils/objectAssign'
export * from '../../utils/PromiseType'
export * from '../../utils/compareString'
export * from '../../utils/isObjectWithKeys'
export * from '../../utils/stringifyStringArray'
export * from '../../utils/unique'
export * from '../../utils/filesystemPathHandling'
export * from '../../utils/getOutDirs'
export * from '../../utils/capitalizeFirstLetter'
export * from '../../utils/debugGlob'
export * from '../../utils/isSameErrorMessage'
export * from '../../utils/styleFileRE'
export * from '../../utils/isPropertyGetter'
export * from '../../utils/debug'
export * from '../../utils/urlToFile'
export * from '../../utils/getGlobalObject'
export * from '../../utils/freezePartial'
export * from '../../utils/isNpmPackage'
export * from '../../utils/isNotNullish'
export * from '../../utils/isScriptFile'
export * from '../../utils/removeFileExtention'
export * from '../../utils/objectKeys'
export * from '../../utils/objectEntries'
export * from '../../utils/objectFromEntries'
export * from '../../utils/getFileExtension'
export * from '../../utils/assertIsNotProductionRuntime'
export * from '../../utils/virtual-files'
export * from '../../utils/path-shim'
export * from '../../utils/assertNodeEnv'
export * from '../../utils/isHtml'
export * from '../../utils/warnIfErrorIsNotObject'
export * from '../../utils/stripAnsi'
export * from '../../utils/getTerminWidth'
export * from '../../utils/truncateString'
export * from '../../utils/formatHintLog'
export * from '../../utils/joinEnglish'
export * from '../../utils/isArrayOfStrings'
export * from '../../utils/escapeHtml'
export * from '../../utils/normalizeHeaders'
export * from '../../utils/isVikeReactApp'
export * from '../../utils/getPropAccessNotation'
export * from '../../utils/PROJECT_VERSION'
export * from '../../utils/genPromise'
