// Utils needed by Client Routing.

// DO NOT include `utils/*` that are only needed by vite-plugin-ssr's server-side runtime.

export * from '../../utils/getBaseUrl'
export * from '../../utils/isExternalLink'
export * from '../../utils/throttle'
export * from '../../utils/getUrlPathname'
export * from '../../utils/serverSideRouteTo'
export * from '../../utils/getCurrentUrl'
export * from '../../utils/assert'
export * from '../../utils/hasProp'
export * from '../../utils/isBrowser'
export * from '../../utils/objectAssign'
export * from '../../utils/parseUrl'
export * from '../../utils/projectInfo'
export * from '../../utils/PromiseType'
export * from '../../utils/slice'
export * from '../../utils/isCallable'
export * from '../../utils/isObject'
export * from '../../utils/isPlainObject'
export * from '../../utils/isExternalLink'
export * from '../../utils/detectHydrationSkipSupport'
export * from '../../utils/PromiseType'
export * from '../../utils/isSameErrorMessage'
export * from '../../utils/sleep'
export * from '../../utils/getGlobalObject'
export * from '../../utils/assertPackageInstances'
