name: "✨ Polish"
description: Docs unclear? Error message confusing? Feature hard to use? Let us know so that we can polish Vike.
labels: ["polish :sparkles:"]
body:
  - type: textarea
    attributes:
      label: Description
