// Utils needed by vite-plugin-ssr's server-side runtime.

// DON'T include `util/*` that used only by the client-side.
// DON'T include `plugin/helpers/*` which are used only by vite-plugin-ssr's Vite plugin. (The Vite plugin code is only loaded/needed in dev and while building; it is not and should be a server-side runtime requirement.)

/* Track down log origins
import '../utils/trackLogs'
//*/

export * from '../utils/assert'
export * from '../utils/cast'
export * from '../utils/checkType'
export * from '../utils/isCallable'
export * from '../utils/isBrowser'
export * from '../utils/isNodejs'
export * from '../utils/isPlainObject'
export * from '../utils/isPromise'
export * from '../utils/hasProp'
export * from '../utils/normalizePath'
export * from '../utils/parseUrl'
export * from '../utils/slice'
export * from '../utils/sorter'
export * from '../utils/projectInfo'
export * from '../utils/isObject'
export * from '../utils/objectAssign'
export * from '../utils/PromiseType'
export * from '../utils/compareString'
export * from '../utils/isObjectWithKeys'
export * from '../utils/stringifyStringArray'
export * from '../utils/unique'
export * from '../utils/moduleExists'
export * from '../utils/filesystemPathHandling'
export * from '../utils/getOutDirs'
export * from '../utils/capitalizeFirstLetter'
export * from '../utils/loadModuleAtRuntime'
export * from '../utils/debugGlob'
export * from '../utils/isSameErrorMessage'
export * from '../utils/styleFileRE'
export * from '../utils/hasPropertyGetter'
export * from '../utils/debug'
export * from '../utils/urlToFile'
export * from '../utils/getGlobalObject'
export * from '../utils/callHookWithTimeout'
export * from '../utils/isStemPackageName'
export * from '../utils/freezePartial'
export * from '../utils/isNpmPackageName'
export * from '../utils/isNotNullish'
export * from '../utils/isScriptFile'
export * from '../utils/removeFileExtention'
export * from '../utils/objectEntries'
export * from '../utils/isStringRecord'
export * from '../utils/getFileExtension'
export * from '../utils/assertServerEnv'
export * from '../utils/virtual-files'
