main="./worker/index.js"
name = "vike_worker-example"
compatibility_flags = ["streams_enable_constructors"]
compatibility_date = "2025-08-06"
workers_dev = true

[site]
bucket = "./dist/client"

[dev]
port = 3000
