export { server }
export type { ServerFetchable }

import { getGlobalContextServerInternal, initGlobalContext_renderPage } from './globalContext.js'
import { assert, assertUsage } from '../../utils/assert.js'
import { hasProp } from '../../utils/hasProp.js'
import { isCallable } from '../../utils/isCallable.js'
import pc from '@brillout/picocolors'
import '../assertEnvServer.js'

type ServerFetchable = {
  fetch: (request: Request, ...args: any[]) => Promise<Response>
}

/**
 * Your server: your `+server.js` composed by Vike.
 *
 * For example, use it inside `+serverEntry.js` to start your server.
 *
 * https://vike.dev/serverEntry
 */
const server: ServerFetchable = {
  async fetch(request, ...args) {
    const handler = await loadServerHandler()
    return await handler.fetch(request, ...args)
  },
}

// virtual:ud:catch-all is generated by Vite, so it's loaded by the global entry (generated by Vite as well) — see getCodeServer() in generateVirtualFileGlobalEntry.ts
async function loadServerHandler() {
  // Loads dist/server/entry.mjs (if not already loaded), like renderPage()
  await initGlobalContext_renderPage()
  const { globalContext } = await getGlobalContextServerInternal()
  const virtualFileExportsGlobalEntry = globalContext._virtualFileExportsGlobalEntry
  assert(hasProp(virtualFileExportsGlobalEntry, 'loadVirtualFileUniversalDeployCatchAll'))
  const { loadVirtualFileUniversalDeployCatchAll } = virtualFileExportsGlobalEntry
  assertUsage(
    loadVirtualFileUniversalDeployCatchAll,
    `${pc.cyan("import { server } from 'vike'")} requires ${pc.cyan('+server')} — see https://vike.dev/server`,
  )
  assert(isCallable(loadVirtualFileUniversalDeployCatchAll))
  const moduleExports: unknown = await loadVirtualFileUniversalDeployCatchAll()
  assert(hasProp(moduleExports, 'default', 'object'))
  const handler = moduleExports.default
  assert(hasProp(handler, 'fetch', 'function'))
  return handler as ServerFetchable
}
