export { pluginCatchAllProdOptions }

import type { Plugin } from 'vite'
import { pluginCommon } from './common.js'
import '../../assertEnvVite.js'

// Matches both `virtual:ud:catch-all` and `virtual:ud:catch-all?default`
const re_catchAll = /virtual:ud:catch-all(?:\?default)?/
// Matches `export default {` with any surrounding whitespace
const re_exportDefault = /export\s+default\s*\{/

/**
 * Transforms the `virtual:ud:catch-all` module generated by `@universal-deploy/vite` to eagerly
 * import the user's `+server.ts` and expose its `prod.*` options (onCreate, onReady, port,
 * hostname, …) on the module's default export.
 *
 * Without this plugin `@universal-deploy/node`'s `startServer()` reads `prod.onCreate` and
 * `prod.onReady` directly from `virtual:ud:catch-all`'s default export, but those hooks live
 * inside a lazy-loaded entry chunk that is only imported on the first HTTP request — so they are
 * always `undefined` at server startup.
 *
 * This plugin fixes three related issues at once:
 * 1. `prod.onCreate` and `prod.onReady` hooks are now called by `startServer()`.
 * 2. Module-level `await` in `+server.ts` (e.g. DB migrations) now runs before the server starts
 *    listening, because the entry is eagerly imported.
 * 3. `prod.port` and `prod.hostname` are now forwarded to `srvx`'s `serve()`.
 *
 * Implementation note: `pluginUnwrapProdOptions` already wraps `serverFilePath` so that its
 * default export is `{ ...originalDefault, ...originalDefault.prod }`. All `prod.*` properties
 * are therefore available directly on `__vikeServerMod` without a second spread.
 * The routing `fetch` (defined last in the object literal) overrides any `fetch` from the user's
 * server entry, preserving correct request routing.
 *
 * Note: Uses traditional Vite/Rollup function-style transform hook (not the Rolldown filter
 * object form) because Rolldown's `transform.filter.id` does not match virtual module IDs that
 * are non-filesystem strings — the filter is only applied to resolved filesystem paths.
 */
function pluginCatchAllProdOptions(serverFilePath: string): Plugin {
  return {
    name: 'vike:pluginUniversalDeploy:catchAllProdOptions',
    // Traditional function form — works for both Rollup and Rolldown/Vite 8 virtual modules
    transform(code, id) {
      if (!re_catchAll.test(id)) return null
      const serverImport = JSON.stringify(serverFilePath)
      // 1. Prepend an eager import of the user's server entry.
      // 2. Spread the server entry (with prod.* already unwrapped) into the catch-all default
      //    export object, before the routing `fetch` so the routing fetch takes precedence.
      const newCode =
        `import __vikeServerMod from ${serverImport};\n` +
        code.replace(re_exportDefault, 'export default { ...__vikeServerMod,')
      return { code: newCode, map: null }
    },
    ...pluginCommon,
  }
}
