name: Auto-merge Dependabot PRs

on:
  workflow_run:
    workflows: ['CI']
    types: [completed]

jobs:
  auto-merge-dependabot:
    # Only run if CI succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Merge Dependabot PR
        uses: "pascalgn/automerge-action@v0.16.4"
        env:
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_FILTER_AUTHOR: "dependabot"
          MERGE_LABELS: "dependencies"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
