name: Spellcheck
on: [ push, pull_request ]
jobs:
  main:
    # Prevent workflow being run twice for same-repo PRs.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - run: pnpm install
      - run: pnpm run spellcheck:check
