name: Publish new Release

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**/CHANGELOG.md'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish_package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    environment: release
    steps:
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.13
      - uses: actions/checkout@v6
        with:
          fetch-depth: 2
      - name: Create GitHub release
        run: |
          for file in $(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep CHANGELOG.md); do
            package_dir=$(dirname $file)
            echo "Syncing GitHub releases for package directory: $package_dir"
            bun ./.github/workflows/sync-github-releases/sync-releases.ts $package_dir
          done
        env:
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITHUB_TOKEN: ${{ github.token }}
